oneup_flysystem:
    adapters:
        media:
            local:
                directory: '%kernel.project_dir%/var/files/media'
        tmp:
            local:
                directory: '%kernel.project_dir%/var/files/tmp'
    filesystems:
        media:
            adapter: media
        tmp:
            adapter: tmp
