security:

    encoders:

        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext

    providers:

        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: ROLE_USER

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            stateless: true

        login:
            anonymous: true
            json_login:
                check_path: /login
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                success_handler: lexik_jwt_authentication.handler.authentication_success
            pattern:  ^/login
            provider: in_memory
            stateless: true

        main:
            anonymous: ~
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            provider: in_memory
            stateless: true

    access_control:
        - { path: ^/media/(.+)/content$ , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ , roles: ROLE_USER }
