#!/bin/sh
set -e

if [ ! -f var/jwt/private.pem ] || [ ! -f var/jwt/public.pem ] ; then
    mkdir -p var/jwt
    rm -f var/jwt/*.pem
    openssl genrsa -aes256 -out var/jwt/private.pem -passout "pass:${JWT_PASSPHRASE}" 4096
    openssl rsa -in var/jwt/private.pem -out var/jwt/public.pem -passin "pass:${JWT_PASSPHRASE}" -pubout
fi
